### ISSUE TITLE
Productpage action conflict met Helm Releaser action?

### ISSUE THREAD

**Issue by sgort** [OpenCatalogi/productpage-action#1]
Op regels.overheid.nl wordt gh-pages branch automatically built by the Helm Releaser GitHub Action én is de bijbehorende github page deployed.

Hoe nu de `OpenCatalogi/productpage-action` te configureren?

Zie PR https://github.com/MinBZK/regels.overheid.nl/pull/393

**Comment by MWest2020** [comment]
Hey @sgort gekeken naar die PR, maar dat is in principe wat we nu als action hebben. Wat wil je precies eraan aanpassen? En doe vooral een PR, kijken we eraan.

**Comment by sgort** [comment]
Kan gesloten worden. Inmiddels de action aangepast zodat ie géén github page aanmaakt. Ik kijk het even aan met enkel een publiccode action, waarbij de Open Catalogi page op organisatie pagina van [MinBZK zelf](https://github.com/MinBZK/.github/pull/13)
